# Generated by Django 4.1.6 on 2023-02-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StripePayment', '0003_currency_alter_order_options_remove_order_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='discount',
            name='name_id',
            field=models.CharField(default=1, max_length=15, verbose_name='ID промокода'),
            preserve_default=False,
        ),
    ]
